# Generated by Django 3.1.6 on 2021-02-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeakevidenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(default=None, upload_to='')),
            ],
            options={
                'ordering': ['files'],
            },
        ),
    ]
